### ISSUE TITLE
 (cl-vulkan-demo::run) => Invalid index 4 for (SIMPLE-VECTOR 4) , should be a non-negative integer below 4.   

### ISSUE THREAD

**Issue by olegharput** [awolven/cl-vulkan#5]
Invalid index 4 for (SIMPLE-VECTOR 4) , should be a non-negative integer below 4.
   [Condition of type SB-KERNEL:INDEX-TOO-LARGE-ERROR]

**Comment by awolven** [comment]
The cl-vulkan-demo has bit rotted since it hasn't been used since 2018.  I have since been writing a graphics engine (krma) and a gui on top the noglfw branch of cl-vulkan, and plan to make the noglfw branch the master branch.  The noglfw branch depends on clui, which is a Lisp replacement for glfw, where clui depends on noffi, which is a project by Gilbert Baumann.  CLUI is mostly done, works with macos, x11 and windows, and just needs some minor fixes to the x11 version.  Right now I'm waiting for Gilbert to have a stable release of noffi.  If you're interested in a Common Lisp Vulkan engine and a gui, I can prepare a build for that, but the demo of cl-vulkan by itself won't be fixed until the merge.
